// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/kv.proto

#ifndef PROTOBUF_service_2fkv_2eproto__INCLUDED
#define PROTOBUF_service_2fkv_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace azino {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_service_2fkv_2eproto();
void protobuf_AssignDesc_service_2fkv_2eproto();
void protobuf_ShutdownFile_service_2fkv_2eproto();

class Value;

// ===================================================================

class Value : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:azino.Value) */ {
 public:
  Value();
  virtual ~Value();

  Value(const Value& from);

  inline Value& operator=(const Value& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Value& default_instance();

  void Swap(Value* other);

  // implements Message ----------------------------------------------

  inline Value* New() const { return New(NULL); }

  Value* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Value& from);
  void MergeFrom(const Value& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Value* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool is_delete = 1 [default = false];
  bool has_is_delete() const;
  void clear_is_delete();
  static const int kIsDeleteFieldNumber = 1;
  bool is_delete() const;
  void set_is_delete(bool value);

  // optional string content = 2;
  bool has_content() const;
  void clear_content();
  static const int kContentFieldNumber = 2;
  const ::std::string& content() const;
  void set_content(const ::std::string& value);
  void set_content(const char* value);
  void set_content(const char* value, size_t size);
  ::std::string* mutable_content();
  ::std::string* release_content();
  void set_allocated_content(::std::string* content);

  // @@protoc_insertion_point(class_scope:azino.Value)
 private:
  inline void set_has_is_delete();
  inline void clear_has_is_delete();
  inline void set_has_content();
  inline void clear_has_content();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr content_;
  bool is_delete_;
  friend void  protobuf_AddDesc_service_2fkv_2eproto();
  friend void protobuf_AssignDesc_service_2fkv_2eproto();
  friend void protobuf_ShutdownFile_service_2fkv_2eproto();

  void InitAsDefaultInstance();
  static Value* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Value

// optional bool is_delete = 1 [default = false];
inline bool Value::has_is_delete() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Value::set_has_is_delete() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Value::clear_has_is_delete() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Value::clear_is_delete() {
  is_delete_ = false;
  clear_has_is_delete();
}
inline bool Value::is_delete() const {
  // @@protoc_insertion_point(field_get:azino.Value.is_delete)
  return is_delete_;
}
inline void Value::set_is_delete(bool value) {
  set_has_is_delete();
  is_delete_ = value;
  // @@protoc_insertion_point(field_set:azino.Value.is_delete)
}

// optional string content = 2;
inline bool Value::has_content() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Value::set_has_content() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Value::clear_has_content() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Value::clear_content() {
  content_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_content();
}
inline const ::std::string& Value::content() const {
  // @@protoc_insertion_point(field_get:azino.Value.content)
  return content_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Value::set_content(const ::std::string& value) {
  set_has_content();
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:azino.Value.content)
}
inline void Value::set_content(const char* value) {
  set_has_content();
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:azino.Value.content)
}
inline void Value::set_content(const char* value, size_t size) {
  set_has_content();
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:azino.Value.content)
}
inline ::std::string* Value::mutable_content() {
  set_has_content();
  // @@protoc_insertion_point(field_mutable:azino.Value.content)
  return content_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Value::release_content() {
  // @@protoc_insertion_point(field_release:azino.Value.content)
  clear_has_content();
  return content_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Value::set_allocated_content(::std::string* content) {
  if (content != NULL) {
    set_has_content();
  } else {
    clear_has_content();
  }
  content_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), content);
  // @@protoc_insertion_point(field_set_allocated:azino.Value.content)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace azino

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_service_2fkv_2eproto__INCLUDED
